// examples/kikko-tauri-vue/src/App.vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import Greet from "./components/Greet.vue";

import {
  IMigration,
  migrationsPlugin,
  useInitDb,
  runQuery,
  sql,
  reactiveQueriesPlugin,
} from "@kikko-land/vue";
import { tauriBackend } from "@kikko-land/tauri-backend";
import { currentDb } from "./currentDb";

const createNotesTableMigration: IMigration = {
  up: async (db) => {
    await runQuery(
      db,
      sql`CREATE TABLE notes(id varchar(20) PRIMARY KEY, title TEXT NOT NULL);`
    );
  },
  id: 18,
  name: "createNotesTable",
};

useInitDb(currentDb, {
  dbName: "helloWorld2",
  dbBackend: tauriBackend((dbName) => `${dbName}.db`),
  plugins: [
    migrationsPlugin({ migrations: [createNotesTableMigration] }),
    reactiveQueriesPlugin(),
  ],
});
</script>

<template>
  <div class="container">
    <h1>Welcome to Tauri!</h1>

    <Greet />
  </div>
</template>

<style scoped>
.logo.vite:hover {
  filter: drop-shadow(0 0 2em #747bff);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #249b73);
}
</style>

// examples/kikko-expo-example/App.tsx
import {
  IMigration,
  sql,
  runQuery,
  IInitDbClientConfig,
  reactiveQueriesPlugin,
  migrationsPlugin,
  EnsureDbLoaded,
  DbProvider,
} from "@kikko-land/react";
import { StatusBar } from "expo-status-bar";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { Text } from "./components/Themed";

import useCachedResources from "./hooks/useCachedResources";
import useColorScheme from "./hooks/useColorScheme";
import Navigation from "./navigation";
import React from "react";
import { Platform } from "react-native";

const createNotesTable: IMigration = {
  up: async (db) => {
    const query = sql`
      CREATE TABLE notes (
        id varchar(20) PRIMARY KEY NOT NULL,
        title TEXT NOT NULL,
        content TEXT NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_note_title ON notes(title);
    `;

    await runQuery(db, query);
  },
  id: 1653668686076, // id should be uniq
  name: "createNotesTable",
};

const config: IInitDbClientConfig = {
  dbName: "trong-db",
  dbBackend:
    Platform.OS === "web"
      ? require("@kikko-land/absurd-web-backend").absurdWebBackend({
          wasmUrl: require("@kikko-land/sql.js/dist/sql-wasm.wasm").default,
        })
      : require("@kikko-land/native-expo-backend").nativeExpoBackend(),
  plugins: [
    migrationsPlugin({ migrations: [createNotesTable] }),
    reactiveQueriesPlugin({ webMultiTabSupport: Platform.OS === "web" }),
  ],
};

export default function App() {
  const isLoadingComplete = useCachedResources();
  const colorScheme = useColorScheme();

  return (() => {
    if (!isLoadingComplete) {
      return null;
    } else {
      return (
        <SafeAreaProvider>
          <DbProvider config={config}>
            <EnsureDbLoaded fallback={<Text>Loading db...</Text>}>
              <Navigation colorScheme={colorScheme} />
            </EnsureDbLoaded>
          </DbProvider>
          <StatusBar />
        </SafeAreaProvider>
      );
    }
  })();
}
