// examples/kikko-tauri-vue/src/App.vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import Greet from "./components/Greet.vue";

import {
  IMigration,
  migrationsPlugin,
  useInitDb,
  runQuery,
  sql,
  reactiveQueriesPlugin,
} from "@kikko-land/vue";
import { tauriBackend } from "@kikko-land/tauri-backend";
import { currentDb } from "./currentDb";

const createNotesTableMigration: IMigration = {
  up: async (db) => {
    await runQuery(
      db,
      sql`CREATE TABLE notes(id varchar(20) PRIMARY KEY, title TEXT NOT NULL);`
    );
  },
  id: 18,
  name: "createNotesTable",
};

useInitDb(currentDb, {
  dbName: "helloWorld2",
  dbBackend: tauriBackend((dbName) => `${dbName}.db`),
  plugins: [
    migrationsPlugin({ migrations: [createNotesTableMigration] }),
    reactiveQueriesPlugin(),
  ],
});
</script>

<template>
  <div class="container">
    <h1>Welcome to Tauri!</h1>

    <Greet />
  </div>
</template>

<style scoped>
.logo.vite:hover {
  filter: drop-shadow(0 0 2em #747bff);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #249b73);
}
</style>

// examples/kikko-react-example/App.tsx
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * Generated with the TypeScript template
 * https://github.com/react-native-community/react-native-template-typescript
 *
 * @format
 */

import React from 'react';
import {Text} from 'react-native';

import {enablePromise} from 'react-native-sqlite-storage';
import {sql} from '@kikko-land/query-builder';
import {
  IMigration,
  runQuery,
  IInitDbClientConfig,
  migrationsPlugin,
  reactiveQueriesPlugin,
  DbProvider,
  EnsureDbLoaded,
} from '@kikko-land/react';
import {reactNativeBackend} from '@kikko-land/react-native-backend';
import {Screen} from './components/Screen';

enablePromise(true);

const createNotesTable: IMigration = {
  up: async db => {
    const query = sql`
      CREATE TABLE notes (
        id varchar(20) PRIMARY KEY NOT NULL,
        title TEXT NOT NULL,
        content TEXT NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_note_title ON notes(title);
    `;

    await runQuery(db, query);
  },
  id: 1653668686076, // id should be uniq
  name: 'createNotesTable',
};

const config: IInitDbClientConfig = {
  dbName: 'trong-db',
  dbBackend: reactNativeBackend({name: dbName => `${dbName}.db`}),
  plugins: [
    migrationsPlugin({migrations: [createNotesTable]}),
    reactiveQueriesPlugin({webMultiTabSupport: false}),
  ],
};

const App = () => {
  return (
    <DbProvider config={config}>
      <EnsureDbLoaded fallback={<Text>Loading db...</Text>}>
        <Screen />
      </EnsureDbLoaded>
    </DbProvider>
  );
};

export default App;
